# nginx.conf
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Обработка SPA (React/Vite)
    location / {
        try_files $uri /index.html;
    }

    # Статические файлы
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }

    # Логи (можно отключить в проде)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}